sudo: required
language: node_js
node_js:
   - "node"

services:
  - redis-server

cache:
  directories:
    - ~/.npm
    - node_modules

notifications:
  email: false

script:
  - yarn
  - yarn lint
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
      node_js: "node"
